spring:
  profiles:
    active: CasaDani
---
spring:
  profiles: CasaDani
  datasource:
    url: jdbc:oracle:thin:@localhost:49161:xe
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    ddl-auto: none
    hibernate:
      dialect: org.hibernate.dialect.Oracle10gDialect
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
---
spring:
  profiles: dbc
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: coworking
    password: coworking
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    ddl-auto: none
    hibernate:
      dialect: org.hibernate.dialect.Oracle10gDialect
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    ddl-auto: none
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    h2:
      console:
        enabled: true
        path: /console
